version: "3.9"
services:

    site:
        image: devandersen/site:latest
        container_name: pi-site
        restart: unless-stopped
        environment:
            GENERAL_LOCAL_IP_ADDRESS: $GENERAL_LOCAL_IP_ADDRESS
            SITE_FTP_ROOT: $SITE_FTP_ROOT
            PIHOLE_ADMIN_PORT: $PIHOLE_ADMIN_PORT
        build:
            dockerfile: ./site/DevAndersen.Pi.Site.Web/Dockerfile
        ports:
            - "80:80"
        volumes:
            - "${GENERAL_FTP_ROOT}:${SITE_FTP_ROOT}"

    ftpserver:
        image: devandersen/pi-ftpserver:latest
        container_name: pi-ftpserver
        restart: unless-stopped
        environment:
            GENERAL_LOCAL_IP_ADDRESS: $GENERAL_LOCAL_IP_ADDRESS
            FTPSERVER_PASSIVEPORTS_FROM: $FTPSERVER_PASSIVEPORTS_FROM
            FTPSERVER_PASSIVEPORTS_TO: $FTPSERVER_PASSIVEPORTS_TO
            FTPSERVER_USERNAME: $FTPSERVER_USERNAME
        build:
            dockerfile: ./ftpserver/Dockerfile
            args:
                FTPSERVER_USERNAME: $FTPSERVER_USERNAME
                FTPSERVER_PASSWORD: $FTPSERVER_PASSWORD
        volumes:
            - '${GENERAL_FTP_ROOT}:/files/'
        ports:
            - "20-21:20-21"
            - "${FTPSERVER_PASSIVEPORTS_FROM}-${FTPSERVER_PASSIVEPORTS_TO}:${FTPSERVER_PASSIVEPORTS_FROM}-${FTPSERVER_PASSIVEPORTS_TO}"

    pihole:
        image: pihole/pihole:latest
        container_name: pi-pihole
        restart: unless-stopped
        environment:
            WEBPASSWORD: $PIHOLE_ADMIN_PASSWORD
            WEB_PORT: $PIHOLE_ADMIN_PORT
        volumes:
            - "./pihole/etc-pihole/:/etc/pihole/"
        ports:
            - "53:53/tcp"
            - "53:53/udp"
            - "67:67/udp"
            - "$PIHOLE_ADMIN_PORT:$PIHOLE_ADMIN_PORT/tcp"
        cap_add:
            - NET_ADMIN
