name: Pull, update, and start local environment

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: docker compose up --build -d
