name: Pull, update, and start local environment

on:
  push:
    branches: [ "main", "github-workflow" ]
  pull_request:
    branches: [ "main", "github-workflow" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Test
      run: pwd
