name: Sync

on:
  push:
    branches: [ "new-runner" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Sync
        run: |
          cd "$HOME/pi-setup"
          git pull
          sh "$HOME/pi-setup/setup.sh"
