name: Sync

on:
  push:
    branches: [ "new-runner" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Run a one-line script
        run: cd "$HOME/pi-setup" && sh "$HOME/pi-setup/setup.sh"
